### ISSUE TITLE
Ads Push

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-ads#137]
## Scoped

- [x] [P2 about GAM](https://newsprojectp2.wordpress.com/2021/03/18/ads-and-google-ad-manager-basics/)
- [x] Newspack-Google OAuth2 flow (https://github.com/Automattic/newspack-plugin/pull/935)
- [x] Handling Ad Units from GAM (https://github.com/Automattic/newspack-plugin/pull/936, https://github.com/Automattic/newspack-ads/pull/124)
- [x] Managing Targeting options ("key-values" in GAM) in Newspack (#78) 
- [x] UI: Control all placements in one place (Newspack Theme placements, widgets, Super Cool Ad Inserter, Ad block) (#177) (#115)
- [ ] Header bidding ([p2](https://newsprojectp2.wordpress.com/2021/04/23/header-bidding-and-how-we-get-there/)) (#209)

## Unscoped
- [ ] Obviate the need to switch to GAM UI for most tasks - a publisher should not have to leave Newspack UI (#194)
- [ ] Create a sitewide ads template that can be activated with minimal effort (#210) 
- [ ] Direct-sold content (integrate w/ Listings, Sponsors)
- [ ] Ad creative creation in Gutenberg

---

- [source 1](https://docs.google.com/document/d/1im-w0CN6uYI1kkICpDuM9wjAgmVhJWxTHjmC-pjHc8o/edit)

**Comment by kmwilkerson** [comment]
Closing in favor of our [current milestones](https://github.com/Automattic/newspack-ads/milestones)
